# yml, yaml이 좋은 이유
# 1. 한글 작성이 용이하다(UTF-8 기준)
# 2. 들여쓰기(가독성) 및 동일한 코드 반복을 줄여줌(중복 X)
# 3. 주석을 작성할 수 있고 들여쓰기를 기준으로 주석처리를 할 수 있다 (아래처럼 중간 단계의 주석을 따로 표시 가능)
test:
  value: def
#    name1:
#      name2:
#      name3:
  age: 10
server:
  port: 8888