server:
  port: 8001

spring:
  application:
    name: eureka-client

eureka:
  client:
    # ? ??? ?? ?? eureka server? ??
    register-with-eureka: true
    # 30??? ?? client? ?????? ??
    fetch-registry: true
    # clinet? ??? ?? ??? ??
    service-url:
      defaultZone: http://localhost:8761/eureka

