# gateway?? ??? ????? ???? ??
server:
  port: 8888

spring:
  application:
    name: config-server
  #   config ?? ??
  cloud:
    config:

      # ?? ??? ?? local repository? ?? - config ??? ?? msaconfig.yml? git? commit? ????(.git?? ??)
      # ? 1?? commit? ???? ??? ???? ( config ??? ??? ??? ??? ????? ?)
      server:
        git:
          # ?? ??? ???? ??? ??? ???? ?
          uri: file:////Users/hyeok/desktop/lecture/github/WEB/MSA/config
