# ?? ???, request ???? ??? ?? ???? ??? ? ??.
# https://docs.spring.io/spring-boot/appendix/application-properties/index.html?? ??? ???? OK
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB