server:
  port: 8111

spring:
  application:
    name: swcamp-user-service

  ## db config
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/menudb
    username: swcamp
    password: swcamp

  ## jpa config
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

hello:
  message: Welcome to 9th SW-Camp

# Token config(나중에 config 서버로 뺼 예정)
token:
  expiration_time: 43200000 # 만료 기간 설정 - miliseconds 딘위(12시간)
  secret: YY0PYolk92oOgGlgSLs9DiW40vJR6tMxlgaMbEeIQPN4mGxtgvoUmvEps+Wnnv+USWZHldQPf//AoPWK15qRBw==  # HMAC secret 키