server:
  port: 0

spring:
  application:
    name: swcamp-user-service

  ## db config
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/menudb
    username: swcamp
    password: swcamp

  ## jpa config
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

hello:
  message: Welcome to 9th SW-Camp

# Token config
# 시크릿 키와 같이 Token 정보는 github에 올리면 안되는 자료이므로, 따로 config 파일에 담아서 외부인이 볼수 없도록 설정
#token:
#  expiration_time: 43200000 # 만료 기간 설정 - miliseconds 딘위(12시간)
#  secret: K0HHLFxls3IXU9tafT999JvEC3c80Dhy7qv41YyY99Pe1agCbJyiv558uBWHTQiYzRDdju9/CLtZltizLjGgSQ==  # HMAC secret 키

## localhost:8000/user-service/actuator/beans 와 같은 형태로 보내면 자동으로 갱신해줌
## actuator 추가 이후 0 - refresh는 POST요청 / beans는 GET요청
management:
  endpoints:
    web:
      exposure:
        include: refresh, beans